### ISSUE TITLE
Ctrl+Y clashes with Redo

### ISSUE THREAD

**Issue by howprice** [jchown/yellow-snow-vscode#3]
Hi Jason

Using v0.13.0 on Windows. I couldn't get Alt-Y to work, but it seems like Ctrl-Y is the Windows shortcut (contrary to the docs). However, this is the standard keyboard shortcut in many applications for Redo. I couldn't get used to Ctrl+Shift+Z so I have this mapped locally (I think). Is it possible to remap the shortcut for this extension?

**Comment by jchown** [comment]
Thanks for trying it out Howard! I've corrected the Windows key binding so it now matches the instructions (Alt-Y) in v0.14.

You can change it to whatever you like using [VS Code's key mapper](https://code.visualstudio.com/docs/getstarted/keybindings).

**Comment by howprice** [comment]
Updated and Alt-Y working. Thanks very much.
